### ISSUE TITLE
Double check wildcard routing

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#1046]
Whilst it's not great practice, people use wildcard() a fair bit to port their apps from 1.x

When using these routes
```
.post(name="wildcard3", pattern="/[controller]/[action]/[key]")
.post(name="wildcard2", pattern="/[controller]/[action]")
.post(name="wildcard1", pattern="/[controller]/", action="index")
.get(name="wildcard3", pattern="/[controller]/[action]/[key]")
.get(name="wildcard2", pattern="/[controller]/[action]")
.get(name="wildcard1", pattern="/[controller]/", action="index")
```
Using no route name misses out the `key`.
Same issue for `wildcard()` (which essentially generates identical routes).
```
with route name
<br />#urlFor(route="wildcard1", controller="test1")#
<br />#urlFor(route="wildcard2", controller="test1", action="test2")#
<br />#urlFor(route="wildcard3", controller="test1", action="test2", key=1)# <---  key works
<br />
without route name
<br />#urlFor(controller="test1")#
<br />#urlFor(controller="test1", action="test2")#
<br />#urlFor(controller="test1", action="test2", key=1)# <--- key doesn't work
```

**Comment by andoradmiraal** [comment]
Had a hard time getting our applications to work using v2.2, but I think that's mainly because we relied on wildcards and never really bothered to properly wrap our heads around the v2 route system. I think I've got it now, but perhaps I'm making a remark below that reflects a lack of full comprehension of the new routing system. 

With that being said, we found the same as mentioned above, except in the last two examples, not just the key, but also the action is missing. Below a few routes, and the resulting URLfor() (same is reflected in redirectTo() and linkTo(), which I think rely on URLfor). If I understand the system correctly, most of these are not what they should be?

**Function used**
#URLFor(controller="authentication", action="loginAuthor")#

**Results**
_No route specified_ 
/authentication

_Route is .get(name="authorvalidation", controller="authentication", action="loginAuthor")_
/authorvalidation <--- returns the name of the route rather than controller and/or action

_Route is .get(name="authorvalidation", controller="authentication", action="loginAuthor", pattern="authentication/loginauthor)_
/authentication/loginauthor <--- seems correct

**Function used**
#URLFor(route="authorvalidation", controller="authentication", action="loginAuthor")# <-- i.e., added the route argument

**Results**
_No route specified_ 
error <-- seems correct (duh!)

_Route is .get(name="authorvalidation", controller="authentication", action="loginAuthor")_
/authorvalidation

_Route is .get(name="authorvalidation", controller="authentication", action="loginAuthor", pattern="authentication/loginauthor)_
/authentication/loginauthor <--- seems correct

**Comment by neokoenig** [comment]
I've added a couple of tests for URLFor without the route names, and it works properly if wildcard is used with mapKey;
i.e.
```
mapper
  .wildcard(mapKey = true)
.end()
```
Will match
```
/example/index
urlFor(controller = "Example");
/example/my-action
urlFor(controller = "Example", action = "MyAction");
/example/my-action/123
urlFor(controller = "Example", action = "MyAction", key = 123);
```
I think the confusion is trying to use single `get()` `post()`'s to replicate this behaviour?

**Comment by bpamiri** [comment]
The current code is reliant on not only the routes definition but also the contents of the params structure. Which may be why the tests are not catching the issue.

**Comment by bpamiri** [comment]
This was handled in 2.3.0-rc.1
