### ISSUE TITLE
Add test framework methods to API docs

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#1132]
Add the following test framework methods to the API docs.

- assert()
- raised()
- debug()
- setup()
- teardown()
- beforeAll()
- afterAll()
- packageSetup()
- packageTeardown()

The only way to find them is either seaching the github repo `/wheels/tests/` directory or scrolling through https://guides.cfwheels.org/cfwheels-guides/working-with-cfwheels/testing-your-application 

It seems `processRequest` is already documented

**Comment by zainforbjs** [comment]
@chapmandu I have added the functions in the API docs.

I just added the Test folder cfc file in the documentscope so that the function that creates documents also parse those functions as well.

Here is a reference to the commit.
https://github.com/cfwheels/cfwheels/commit/c2a5155a2d0776761f1db38eb498b3176ca34fad
