### ISSUE TITLE
1.2 findAll() select doesn't like single quotes - MySQL

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#168]
This code works in 1.1.8

select="campaigns.id AS id, CONCAT(campaigns.name, ' - (', customers.name, ')') AS name"

throws error

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM campaigns INNER JOIN customers AS customers ON campaigns.customerid = custo' at line 2
SQL SELECT campaigns.id AS id,CONCAT(campaigns.name 
FROM campaigns INNER JOIN customers AS customers ON campaigns.customerid = customers.id AND customers.deletedat IS NULL 
WHERE 
( 
customers.agencyid = 
1 
) AND ( 
campaigns.deletedat IS NULL 
) 
ORDER BY campaigns.name ASC

**Comment by blastiko** [comment]
Hi guys
This issue is already present in v.2.5.1.
This code:
`var q=model("table").findAll(select="CONCAT(table.col_one,'-',table.col_two) AS cres");`
return this error:
Wheels.ColumnNotFound
Wheels looked for the column mapped to the ' - ' property but couldn't find it in the database table.
Vers. 2.4.0 is not affected.
