### ISSUE TITLE
Allow a class attribute on each option for the select and selectTag helpers

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#281]
This will require a "class" column/struct element in the options passed. Would this be something that would be "core appropriate" or is this more a plugin type thang?

**Comment by perdjurner** [comment]
Implement like this:

Look for any argument starting with "option".
If it's a list, apply to each option tag, otherwise apply the same to all of them.
Also, remove the "es" or "s" (if logically possible) on the argument name when a list is passed in.

This would end up supporting the following calls for example:

selectTag(name="x", options="1,2,3", optionClass="class-name")
selectTag(name="x", options="1,2,3", optionClasses="class-name-1,class-name-2,class-name-3")

selectTag(name="x", options="1,2,3", optionId="id-name")
selectTag(name="x", options="1,2,3", optionIds="id-name-1,id-name-2,id-name-3")

Do the same for other view helpers that produce more than one element.

We already have this on "labelClass" for form helpers for example so use this new code for that as well when done to keep things DRY.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
