### ISSUE TITLE
UTC support

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#293]
Global setting?
Backport Andy's commits?
See how Rails handles it.

**Comment by jkeczan** [comment]
We implemented UTC conversion in our system and it has worked very well.

We store the UTC time in the database. On query, we simply use afterFind in the Model.cfc to convert the time to the proper timezone based on userID and column type. We maintain a list of default columns that must be converted such as dateCreated and dateModified.

It works very well and is very easy to implement. We could incorporate this into CFWheels easily by simply having a useUTCTime flag. If it is set, simply use the default columns in CFWheels for dateCreated and dateModified. If they have been overridden, just use those instead.

**Comment by perdjurner** [comment]
Could you make a plugin you think?

(That we can later evaluate and see if it should be included in core instead.)

**Comment by jkeczan** [comment]
I can give it shot. I will see if I can have it done by end of next week.

**Comment by chrisdpeters** [comment]
In Rails, you typically set the time zone in one of two places (or both, I suppose):

1. A config value in `config/application.rb` sets the default time zone globally:
```ruby
# Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
# Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
config.time_zone = 'Central Time (US & Canada)'
```
I believe even with this set, the database still stores UTC time for everything, but then Active Record converts to Central Time after find.

2. The controller, based on whatever data you want. Here's an example as a before filter:
```ruby
class ApplicationController < ActionController::Base
  before_action :set_user_time_zone

  # Sets time zone based on user's setting
  def set_user_time_zone
    Time.zone = current_user.time_zone if user_signed_in? && current_user.time_zone.present?
  end
end
```
The first option would be easily taken care of with a setting in addition to @jkeczan's suggestion of the `set(useUtcTime=true)` flag. But I would argue that there should be another setting that tells it what to auto-convert to by default after querying. Perhaps `set(defaultTimeZone="Central Time (US & Canada)")`.

I think it's pretty important to allow the flexibility of the 2nd option. Some applications will want to do this in a very specific way. (URL param? Session value? Column in signed-in user's record? Leave it up to the implementer.) The controller is the best place for this logic since another persistence store (even a temporary one like the session) may be in charge of determining what the time zone is.

So perhaps there can be something like this?
```coldfusion
<cfscript>
component extends="Controller" {
  function init() {
    filters(through="setUserTimeZone");
  }

  private function setUserTimeZone() {
    if (userSignedIn() && Len(currentUser.timeZone)) {
      setTimeZone(currentUser.timeZone);
    }
  }
}
</cfscript>
```
Not sure if there's a cleaner way to set request-level values for the model from the controller like that. I was tempted to use `set()` but realized that's for application-level values.

Thoughts?

**Comment by perdjurner** [comment]
@andybellenie This issue can be closed, right?

**Comment by andybellenie** [comment]
Yes, this was fixed in https://github.com/cfwheels/cfwheels/pull/696

Note that default is now UTC, not local (potentially breaking change)
