### ISSUE TITLE
WHEELS.SHOWDEBUGINFORMATION is undefined on shared application name

### ISSUE THREAD

**Issue by scahyono** [cfwheels/cfwheels#359]
When we share application name with legacy application, we got "WHEELS.SHOWDEBUGINFORMATION is undefined" when wheels is started after the legacy application.

How to reproduce:
1) Add the following line into "config/app.cfm"
&lt;cfset this.name="MyApp">
2) Add the same line above into "miscellaneous/Application.cfc"
3) Create "miscellaneous/test.cfm" with these content below:
&lt;form action="../index.cfm?controller=wheels&action=wheels" method="post">
    &lt;input type="submit" value="submit">
&lt;/form>
4) Make sure the Windows/Linux coldfusion service is just freshly started
5) Visit http://127.0.0.1:8500/cfwheels/miscellaneous/test.cfm
6) Click on "submit" button
You will get error "Element WHEELS.EVENTPATH is undefined in APPLICATION."
7) Refresh the page
You will get error "Element WHEELS.SHOWDEBUGINFORMATION is undefined in APPLICATION."

Why this errors matters?
While the above example is simplistic, complex single page ajax application (SPA) might use wheels only for ajax call, while the main page was legacy application sharing the same application name with wheels application.
So, for some complex SPA application, wheels will **_always**_ start second after the legacy application that shared the same name.

**Comment by adamcameron** [comment]
Lads this was never a bug, however the fix for it *is* a bug.

See https://github.com/cfwheels/cfwheels/blob/v2.4.0/wheels/events/onrequeststart.cfm#L8-L11 and https://github.com/cfwheels/cfwheels/blob/v2.4.0/wheels/events/onsessionstart.cfm#L5-L8


Why was it not a bug?

Well *of course* if you start an app called "myApp" from one codebase, then if you run another codebase which also has a name "myApp", then the second app won't have its app environment initialised properly. Why would one ever expect that? It's like passing the wrong value to a function and then complaining the function didn't work properly.

The issue here was just that @scahyono had architected their code suboptimally. If you need two apps to use the same name, then you need to code accordingly: extend one's Application.cfc from the other one so each's lifecycle event handlers can run. Of course doing OO stuff like this in CFWheels is a bit hamstrung due to its lack of OOP considerations in how it's been designed, but this should still be doable. But it's an issue for @scahyono to fix in their app; not for CFWheels to address.

Or... almost certainly having them share the same application name was not the best thing to do in the first place (esp in the case described, I think).


Why is the fix for this a bug?

Running `onApplicationStart` *doesn't restart the app. All it does is run some code in `onApplicationStart`. To restart the app you first need to _stop_ the app (`applicationStop`), and then let the CFML app server handle app restart.

An analogy I use to make this clearer is consider a JS situation... running an onclick handler function doesn't actually make the mouse button depress. Event handlers are things that happen _as a result_ of an event occurring. They are not the event themselves. `onApplicationStart` is an event handler. Not an event.


Why am I telling you this in 2023?

Because this code causes app instability, and it's causing us grief, and now I have to dick around fixing it, when it wasn't broken in the first place.

:-|

**Comment by chapmandu** [comment]
@adamcameron Could you elaborate on the symptoms you're seeing, I'd be interested to know so I can look for similar behaviour. TIA.

**Comment by adamcameron** [comment]
Firstly: I am on 1.4.5 (ish... it's got some 2.2 fixes hacked into it, and a couple of our own shims. Don't ask. It's mostly 1.4.5). However having looked at the code differences, am pretty certain my experiences would still occur on 2.x.

The situation crops up when the application is left unstable, which surfaces as stuff like "application.wheels.[something] doesn't exist" etc. This seems to happen for us during app-start-up under any sort of load (and by that, I just mean "multiple requests", not "shitloads of requests")... it looks to me like multiple requests will end up re-running onApplicationStart, which in turn cause some things to be partly initialised or something. The logic in app start-up is a disorganised mess (sorry), so this does not surprise me.

I think it's down to how Wheels code has a tendency to run `onApplicationStart` directly, which isn't single-threaded, and isn't controlled properly by the CFML server like an app-start-up is supposed to be. Because of probable race conditions in the start-up code, multiple requests end up competing to re-init parts of application.wheels, they conflict, and the app gets crocked.

I do not have a repeatable way to trigger it though, I'm afraid. However it happens 80% the time when the app is restarted. 

I don't have a "live" case I'm dealing with ATM, I just landed on this code because we're ripping out all of the bad app-restart code and doing it properly, and this situation is one of the touchpoints where a bad app-restart happens. I saw the "issue 359" in a comment in the code, and followed it here.

That's probably not much help mate, sorry.
