### ISSUE TITLE
Support Lucee

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#442]

**Comment by neokoenig** [comment]
Ok, there's now a branch called lucee-support where I've made some initial additions changes.
https://github.com/cfwheels/cfwheels/tree/lucee-support

Tests appear to pass locally. Have set the minimum version of Lucee to 4.5.0.42 which is the current stable release.

NB, I think lucee has some sort of internal alias to railo in the server scope, as `StructKeyExists(server, "railo")` equates to true under lucee (I'm not really surprised, probably a backward compatibility thing).

A couple of other of railo specific conditions I've left out, as they were workarounds for version 3.x of railo where they're fixed in 4.x.

Please test!

**Comment by perdjurner** [comment]
:+1:

**Comment by neokoenig** [comment]
Note to all, when you do any checks, Lucee has an alias to Railo in the server struct (but doesn't appear on dump). Confirmed by lucee team at https://groups.google.com/forum/?fromgroups=#!topic/lucee/1asgCDwC_tE

**Comment by perdjurner** [comment]
Merged.
