### ISSUE TITLE
findOne and findFirst with returnAs="query" and include="hasManyAssoc" returns more than one row

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#487]

**Comment by perdjurner** [comment]
I'm pretty sure that's intentional actually. For example, if you ask Wheels for the first "author" in the database and all their "books" I don't see how that can only return 1 record (you would miss lots of books then...)

Wheels behaves the same way with pagination I think, if you ask for 5 authors per page including their books you will get anywhere from 5+ records (not just 5).
