### ISSUE TITLE
Error in Lucee 5 beta

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#497]
Look into this one and either fix or get Lucee to fix it.

See "CFWheels on Lucee" in the Google group for details.

**Comment by perdjurner** [comment]
@neokoenig , maybe something you can have a look at?

**Comment by neokoenig** [comment]
Will do.

**Comment by neokoenig** [comment]
hmm. finding this pretty hard to debug. Is as those the wheels struct in application is just never created  or something.

I initially thought it might be the whole 'railo/lucee' struct Alias thing; They've removed it so that `structkeyexists(server, "railo")` now returns `false` from 4.5.1.003. However, everything seems to work on all 4.5.1.xxx branches, it's the jump to 5.x (any of them, same issue) which is the problem.

I think there's still a lot of bugs/changes in behaviour in 5.x, it's quite a dramatic change from what I recall. Question is whether to carry on trying to debug 5.x in its current (very beta) state, or leave it for a bit till there's a release candidate or stable release.

Thoughts?

**Comment by perdjurner** [comment]
Maybe leave it for a bit and check again when we're closer to releasing our
next version.

**Comment by neokoenig** [comment]
FYI - https://luceeserver.atlassian.net/browse/LDEV-415 bug logged. Will see if the Lucee people have any thoughts.

**Comment by perdjurner** [comment]
Is is strange that they have not even looked at the bug yet or is that kinda of wait time normal you think?

**Comment by neokoenig** [comment]
I'll see if I can ping micha on Slack

**Comment by scahyono** [comment]
I agree this is difficult to debug. The cfwheels unit tests from both master and 1.4 branches cannot pick up this error.
I have tried "mvn clean verify -DluceeVersion=5.0.0.49 -Pjetty,lucee" on both branches.
My result is "Tests run: 43, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.597 sec"

**Comment by neokoenig** [comment]
Fixed in 5.0.0.65 Beta!
