### ISSUE TITLE
Could not find the ColdFusion component or interface plugins.cfwheels.cfwheels

### ISSUE THREAD

**Issue by shreddsultan** [cfwheels/cfwheels#597]
I'm new to cfwheels. I see there is an issue that was closed with the same error but no solution was provided.

I installed cfwheels without any modification. It ran fine and gave me the congratulations page.
I downloaded dbMigrate plugin and got this error on reload. I removed the zip file  and tried to install coldroute plugin - same issue.
When reloading, cfwheels creates the following directory structure (initially an emply /plugins folder):
/plugins/cfwheels/cfwheels-dbmigrate-plugin-master

The dbmigrate.cfc is in the cfwheels-dbmigrate-plugin-master folder along with the index.cfm.

I'm using apache on ubuntu 12.04 with ColdFusion 9.

**Comment by chapmandu** [comment]
It's not an issue with wheels, it's due to the name of the zip file that is generated by github.

Rename your zips to dbmigrate.zip and coldroute.zip

**Comment by perdjurner** [comment]
@chrisdpeters is this something we can improve you think?

**Comment by chrisdpeters** [comment]
@shreddsultan There are a couple things that CFWheels looks for from a plugin:

-  The contents of the plugin must be in the root folder of the plugin. So if you downloaded the source directly from GitHub, you'll notice that the source is within a subfolder. Those contents must be directly in the "root" of the zip file.
-  The zip file must be named `[PluginName]-[version].zip`. This must match the name of the main CFC within. So, for example: `coldroute-0.3.zip`. If you're using Linux, it must match the exact casing of the main CFC's file name as well.

For DBMigrate, I recently created a proper zip file under the "downloads" section of the latest [release](https://github.com/tdm00/cfwheels-dbmigrate-plugin/releases). Give that one a try. I could do the same thing for ColdRoute too, I believe.

@perdjurner @chapmandu There are many ways that we can improve this. The best long-term solution I believe would be to get the CFWheels plugin system integrated with a package manager like CommandBox. Managing versions and dependencies of plugins is a pain in the ass, and this whole business of fishing around on GitHub is not very good in my opinion.

In the short term, we could have plugins loosen up a little, but I feel like it doesn't solve some of the pain points of managing these dependencies. One thing we could do is have the CFWheels plugin loader go within a subfolder to look for the plugin, but I'm not sure how it would know what to look for after that because the GitHub project isn't always named after the plugin CFC exactly.

**Comment by neokoenig** [comment]
I hit this problem when trying to put together a plugins repo; completely inconsistent git repos; some people have a folder called `/releases/` with zips in them, some people use the gitHub release system, some have a `src` folder and no compiled zip, and some people do none of the above.

**Comment by chrisdpeters** [comment]
@neokoenig Right. You cannot rely on the plugin authors' Git repos at all. This is why I liked having the plugin directory on cfwheels.org that forced authors to publish their zip files manually. The website even validated that the contents within the zip files were roughly correct.

We could create our own package manager for the plugins as well. That's not out of the realm of possibility. It could work similarly to Bower.

**Comment by shreddsultan** [comment]
Thank you Chris for the download and the explanation. DBMigrate works now.
