### ISSUE TITLE
Answer OPTIONS requests properly

### ISSUE THREAD

**Issue by chrisdpeters** [cfwheels/cfwheels#623]
I'll be honest and admit that I wasn't 100% sure what the `OPTIONS` HTTP verb did, so I found [this post](http://zacstewart.com/2012/04/14/http-options-method.html) about the subject.

After ColdRoute is integrated into core (#609), I think it would be relatively trivial for CFWheels to do this automatically.

I see this more as a v2.1 feature, so I'm not going to schedule for the 2.0.0 milestone. I'd rather focus on just getting the existing plugin functionality working for the v2 release. That'll be tricky enough on its own. :)

**Comment by dbelanger** [comment]
Hey Chris, I'm using the 2.0 Beta right now and we will need to make a small change here in order to get the current work-around to be at 100%.  For the moment, we're satisfying CORS by setting the following 3 headers in **.htaccess** or **web.config**:

```
Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Methods "GET, POST, PATCH, PUT, DELETE, OPTIONS"
Header set Access-Control-Allow-Headers "Origin, Content-Type, X-Auth-Token, X-Requested-By, X-Requested-With"
```

This will work for the time being and a 200 is returned for the OPTIONS request, However, when you inspect the packet returned, you'll see a "Route not found error".

May I suggest we add OPTIONS to the wheels/mapper/matching controller and return a blank DATA field to the browser? (for the Beta release)

(2.1) If you did want to take this all the way, we could also simply return the methods for the routes that have been set.  They should be ready to go in the application scope at the time this is called.  You'd just have to loop through and return the ones allowed by the controller call in options.

**Comment by chrisdpeters** [comment]
I don't know that it's as simple as echoing what's in the `application` scope. Let's say I have a resource with authorization logic, and I don't want certain types of users to know about the existence of certain endpoints. (For example, maybe they can access the `show` endpoint but not the `update` or `delete` endpoints.)

We'd probably need to define some sort of controller logic that would instruct what to expose via `OPTIONS` that runs on each request.

**Comment by neokoenig** [comment]
As a side note, me and @perdjurner were discussing `catchall` methods for the new routing system, and the idea of verb specific catchall routes came up.

The idea was to add a `catchAll()` method to `mapper()` which could then respond appropriately to an incorrect route instead of throwing a "Route not found" error. 

So you could have: `mapper().catchall(verb=OPTIONS, to=main#options)` where you could handle the request appropriately. This also works for say, PUT vs PATCH, where you might implement one but not the other, but still want to present a "nice" JSON message for the incorrect verb with an appropriate status code.

**Comment by dbelanger** [comment]
This is from our recent Slack discussion:

Basically, in 2.0, we add the following to the web.config for IIS

```
        <httpProtocol>
            <customHeaders>
                <add name="Access-Control-Allow-Origin" value="*" />
                <add name="Access-Control-Allow-Methods" value="GET, POST, PATCH, PUT, DELETE, OPTIONS" />
                <add name="Access-Control-Allow-Headers" value="Origin, Content-Type, X-Auth-Token, X-Requested-By, X-Requested-With" />
            </customHeaders>
        </httpProtocol>
```

but that's only half the battle in production because, for example, /api/v1/users may exist for a GET, but an OPTIONS AJAX pre-flight request for that URL (which in a lot of cases you can't turn off), would fail in production because the suppressed Wheels missing route error turns into a 404 (which is what I would expect of a CF error in production)

I found a nice little addition to our web.config which will actually avoid any unnecessary processing for OPTIONS while we decide how to handle them

```
                <rule name="OPTIONS" patternSyntax="Wildcard" stopProcessing="true">
                    <match url="*" />
                    <conditions logicalGrouping="MatchAny">
                        <add input="{REQUEST_METHOD}" pattern="OPTIONS" />
                    </conditions>
                    <action type="CustomResponse" statusCode="200" subStatusCode="0" statusReason="OK" statusDescription="OK" />
                </rule>
```

(full credit goes to Sergey Kanzhelev at [](http://apmtips.com/blog/2017/01/31/fast-options-response-using-url-rewrite/)

That rule, placed before our '<rule name="ColdFusion on Wheels URL Rewriting" enabled="true">' rule will save a lot of processing because for an API, there are a lot of pre-flight requests.

**Comment by perdjurner** [comment]
Current milestone is just for responding with 200 to all OPTIONS requests. Then we can improve the functionality in later releases.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
