### ISSUE TITLE
Throw error when passing in object to view helpers

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#629]
This applies to textField() and others.

The following should work:
textField(objectName="user", property="firstName")

This should NOT:
textField(objectName=user, property="firstName")

**Comment by neokoenig** [comment]
What happens when you want to reuse forms for different models?
I often have common fields/form partials where the current model is passed in as an argument:
`textField(objectName=arguments.objectname, property="title", label="Title", placeholder="Main Title")#`

Or are you saying just throw an error when an 'actual' object is passed in as opposed to a variable which contains the objectname?

**Comment by chrisdpeters** [comment]
@neokoenig I think he's referring to passing in an actual object.

**Comment by andybellenie** [comment]
Nice 👍
