### ISSUE TITLE
Improve redirectTo when using back argument

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#667]
A common problem is that redirectTo(back=true) blindly redirects to the value in cgi.http_referer even though that might have been a POST request.

Change this so the redirect is to the last GET request made instead.

**Comment by neokoenig** [comment]
To do this, we would need to manually record what the last `GET` request was somewhere, as the CGI scope won't have that information. So to do this we would need to persist the last GET location across more than one request - am I correct? If so, what would be the best place to store this?

**Comment by andybellenie** [comment]
The flash can be stored in either cookie or session scope, I suggest the same approach

**Comment by neokoenig** [comment]
Doh, yeah of course. Cool, I shall have a stab at this then.

**Comment by neokoenig** [comment]
Hmm. Thinking about this further, it's not 100% simple.

1) If I use the flash, then any call to `flashIsEmpty()` will never or very rarely return true; this will then break most caching
2) Some users might just output the whole flash rather than look for specific keys; this means the developer in this case would need to write an exception for whatever flashkey I ended up using.

Shall carry on having a think

**Comment by andybellenie** [comment]
I wasn't suggesting actually using the flash, only a reminder that we need to allow cookie storage in case the app doesn't support sessions

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
