### ISSUE TITLE
PUT vs PATCH in new routing docs

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#719]
In http://docs.cfwheels.org/v2.0/docs/using-routes there's extensive mention of `PATCH`

i.e
```
.patch(
    name="usersActivate",
    controller="users/[userKey]/activations",
    action="update"
  )
```

However, that gives `component [wheels.Mapper] has no function with name [patch]` ;

Did `patch()` not make it to 2.x or are the docs still in progress?

**Comment by perdjurner** [comment]
Maybe we should only implement PATCH?

See this for more info:
http://jsonapi.org/faq/#wheres-put

If we do, we can just rename "put" to "patch" in our code and remove any reference to PUT in the docs (and perhaps add a note saying to always use PATCH instead of PUT).

@chrisdpeters thoughts?

**Comment by chrisdpeters** [comment]
I think that both methods should be supported because different clients/standards disagree on which should method be used for updates. CFWheels should prefer `PATCH` in its documentation.

`patch` should be added as an alias of `put`. I'm guess that it's not yet in the core because it isn't in ColdRoute.

**Comment by chrisdpeters** [comment]
P. S. That means that `resources` and `resource` should add both `PUT`- and `PATCH`-based routes for update.

**Comment by perdjurner** [comment]
Done in e7edf9a0e6dd2ef73fdce9099dbbb136b913b400.
