### ISSUE TITLE
Add concurrency logic for optimistic locking

### ISSUE THREAD

**Issue by tapirus** [cfwheels/cfwheels#784]
Hi,

I like the way django handles optimistic locking.

https://github.com/saxix/django-concurrency

Maybe this would be useful in wheels also.
tapirus

**Comment by perdjurner** [comment]
Found some old threads that might have some useful info if someone decides to implement this:

https://groups.google.com/forum/#!topic/cfwheels/BsXpbOfOy9k
https://groups.google.com/forum/#!topic/cfwheels/SllOpm3DTdo

Tagging as plugin since I think something like this is suitable for being built as a plugin first and then possibly integrated to core later.

**Comment by perdjurner** [comment]
Closing this as we're using the issue tracker for bugs only from now on.
Please implement your feature suggestion as a plugin or make a pull request.
If you need feedback before starting, please consult the Google Group.

Thanks.
