### ISSUE TITLE
ACF 2016 test suite failure

### ISSUE THREAD

**Issue by perdjurner** [cfwheels/cfwheels#815]
Fails when passing in status to `renderWith()`.
Tests are in `renderwith.cfc`

**Comment by neokoenig** [comment]
FYI, I've narrowed this down to this test:

```
	function test_custom_status_codes_204() {
		params.format = "json";
		params.action = "test2";
		_controller = controller("test", params);
		_controller.provides("json");
		user = model("user").findOne(where="username = 'tonyp'");
		_controller.renderWith(data=user, layout=false, returnAs="string", status=204);
		assert("$statusCode() EQ 204");
	}
```
I think setting the header statuscode to 204 breaks the test suite in ACF2016 due to not returning a correct response. 

I suspect it's actually this ACF bug, see: https://tracker.adobe.com/#/view/CF-4190974 which was fixed in Update 4 (see https://helpx.adobe.com/coldfusion/kb/bugs-fixed-coldfusion-2016-update-4.html ) - for some reason my local commandbox copy isn't letting me update to the latest ACF patch, so can't check if this is the case or not.

**Comment by perdjurner** [comment]
If it's only that 204 test that breaks the test suite I think we should just remove it.
Looks like we have plenty of similar tests in there anyway.

**Comment by neokoenig** [comment]
Yeah, the principle is proved in the other tests. Will remove.
