### ISSUE TITLE
Wheels controller functions not bypassing base controller filters

### ISSUE THREAD

**Issue by andybellenie** [cfwheels/cfwheels#844]
Create base Controller.cfc:

````
<cfcomponent extends="wheels.Controller">

	<cffunction name="config">
		<cfset filters(through="testFilter")>
	</cffunction>

	<cffunction name="testFilter">
		<cfabort>	
	</cffunction>

</cfcomponent>
````

Now browse to http://[appdomain]/rewrite.cfm?controller=wheels&action=wheels&view=routes&type=app

Nothing happens.

Shouldn't Wheels methods like view routes/tests bypass all application specific code?

**Comment by andybellenie** [comment]
My main concern is unexpectedly running app code messing up tests

**Comment by neokoenig** [comment]
Update on this. I've got a local branch here where I've made this work. 

Essentially, two things were needed - 
1) in `/wheels/dispatch/functions.cfm`, do `$include(template="wheels/gui/routes.cfm");` just before the user's routes are loaded - essentially we're adding `wheels/whatever` etc to the main routing table

2) hijack any request where the local controller name is wheels, and instead of init'ing a normal controller class which extends the users app controller,  just create a new CFC for us to use, and route the action through to the method of the new CFC.

/wheels/dispatch/functions.cfm, after `$debugPoint("setup");`
```
	if(listFirst(local.params.controller, '.') EQ "wheels"){ 
		local.rv = $createObjectFromRoot(path="wheels", fileName="gui", method="$initControllerClass", name="wheels");
		local.rv = local.rv[params.action]();
		return local.rv; 
	} else {
... normal wheels request
	}
```

From that point on our new CFC can do whatever. Which is pretty cool. Downsides so far are that the debugging output disappears but I'm sure I can work that out. 

So my next step is to come up with an awesome (perhaps vueJS based) UI so I can rewrite the main internal pages into something more usable...

**Comment by neokoenig** [comment]
Forgot to mention - also has the huge bonus of being able to use the URL rewriting, so `/wheels/routes` actually works, as opposed to having to remember that stupid string of params. Also means we can much more easily add additional features over time

**Comment by neokoenig** [comment]
Closing, as new GUI fixes this
