### ISSUE TITLE
select() fails for multiselect

### ISSUE THREAD

**Issue by reubenbrown13** [cfwheels/cfwheels#909]
I had the need to setup a multiselect option in a form, and I discovered that the form logic breaks when you add the HTML param multiselect="multiselect".  I am working on a solution that works for my use case.  In this instance I have a link table that is used to join the table with the values for the multiselect to the table that holds the record that is being edited.  The only requirement at this time to make it work is that the link table MUST be named based on the 2 tables you are linking.  Example: linking posts to categories would be a table named postCategories.  The ONLY 2 fields needed would be postid and categoryid.  The ID names are based on the tables they reference.  This is also required so the system can reference the table to get the values needed.  If this fix is desired, let me know and I will put it into a pull request.

**Comment by neokoenig** [comment]
I'm not sure I understand the problem you're trying to fix; could you give a simple example?

**Comment by reubenbrown13** [comment]
In the cfwheels example app, edit the users roles form to have the following just after the role selection.
`<div class="col">
	#select(objectName="user", property="userpermissions", multiple="multiple", options=model("permission").findAll(), label="Permissions")#
</div>`

You will be able to make the selections, but only the first entry will be stored, and when the form loads, there will be no selected values based on what is in the database.  When I was first working on another form, I was getting errors also, but in this case, I am not seeing it.

The fix I have allows for this full functionality to work where the linked data will be saved and displayed in the multi-select field.

**Comment by neokoenig** [comment]
I think the issue is that the result of a `select()` where `multiple` is true is that it gives you a comma delimited list of values - and you're saying you want them to be able to be mapped much like the way `hasManyCheckbox()` works?

I think this would need a new form element, like `hasManySelect()` (or something) as it would break all the existing wheels apps which use `multiple` to actually store a comma delimited list of values (think a list of tags)?

I may have misunderstood you of course!

**Comment by reubenbrown13** [comment]
This fix is backwards compatible w/ the comma delimited list.  I wrote it so that it would work w/ those forms too.  I will run a test to make 100% certain, but the fix to have it use the multiple with an object checks to see if an object is being supplied or not for the values.  If not, then it uses the existing logic for the values/options.

**Comment by neokoenig** [comment]
Pinging @andybellenie @chapmandu @dbelanger  for comments

**Comment by chapmandu** [comment]
This has been on my wish list for a long time.. It's like a hasmanycheckbox for selects!

Regards,
Adam

**Comment by andybellenie** [comment]
Agreed

**Comment by neokoenig** [comment]
```
#select(
objectName="book",
association="bookAuthors",
multiple=true,
options=authors,
valueField="#book.key()#,#authors.id#",
textField=authors.fullName
)#
```

or something?

**Comment by dbelanger** [comment]
I think that while Reuben is right that it can be made to work in **select()**, I prefer Tom's approach to creating a new **hasManySelect()** tag.  First, it's consistent with the **hasManyCheckbox()** tag and second because we'd have clear control over what's happening with that tag within one function.  

My other thought is that if we chose to do it above as Rueben suggested, we should consider doing the same for **hasManyCheckbox()** for consistency and deprecating the old tag.

**Comment by neokoenig** [comment]
And presumably `hasManyRadioButton()`

**Comment by reubenbrown13** [comment]
Well.... no matter what, I need to implement a solution...... so I will create a hasManySelect() function that works similar to the hasManyCheckbox() so I can test which works and I can then have both solutions ready to go for your review.

**Comment by reubenbrown13** [comment]
It doesn't work 100% yet, but I have a plugin built that creates a function hasManySelect and uses the BootStrap multiselect w/ checkboxes display to make things look pretty.  I am going to add an option to turn this off if desired and I still need to get it to display the values properly that were stored in the database.  Right now it only shows if there is ONLY 1 entry.  Once I have it working, I will load it into forgebox.io  Should be there soon since this is something I need to get working anyway.

**Comment by reubenbrown13** [comment]
I have loaded the plugin onto forgebox.io : https://www.forgebox.io/view/cfwheels-bootstrapmultiselect-plugin .  The display is not 100% the way I want it, but it does get the job done.
