### ISSUE TITLE
Remove wildcard() route from default wheels install

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#930]
I think we should ditch the wildcard() route in the default wheels installation - it causes more problems than it solves... thoughts?

**Comment by dbelanger** [comment]
That's a tough one Tom because for beginners I like that they can just create their own basic scaffolding and go, just like it used to be.  Once they get comfortable with the MVC, then they can get more secure by controlling their own routes.

Maybe an option in the global settings where we turn routing on or off?  In my mind, "Off" would use the wildcard only.

**Comment by neokoenig** [comment]
True... but to just change the front page you have to set the `root()` to whatever, so you have to start dealing with routes fairly early... hmm
