### ISSUE TITLE
autoMigrateDatabase not running on server start

### ISSUE THREAD

**Issue by neokoenig** [cfwheels/cfwheels#957]
`set(autoMigrateDatabase = true)` doesn't appear to be kicking in on a fresh server start in production mode - only if you actively reload the app whilst in production.  Needs checking.

**Comment by chapmandu** [comment]
I've suspected this too.. but couldn't prove it.

**Comment by chapmandu** [comment]
Could this be something to do with the sort order of migrations.. I had 3 of 6 migrations run in a deployment.. and same behaviour in dev after a restart.

**Comment by chapmandu** [comment]
The issue was explicitly referencing the `application.wheels` scope in `tableDefinition` whilst migrating onapplicationstart. Once the framework has finished loading, the `application.wheels` scope exists and the migrations will work.. which explains the behaviour we were both seeing.. Only happened when doing and autoMigrate and creating a new table.

**Comment by neokoenig** [comment]
You are my personal hero. Great timing  for me :)
