### ISSUE TITLE
Support Custom Configuration Environments

### ISSUE THREAD

**Issue by Andywmm9** [cfwheels/cfwheels#967]
Currently there doesn't appear to be support for a post-test environment (where we test our deployment scripts before moving to production).  Support for custom configuration environments would be ideal for those with other environments.

**Comment by neokoenig** [comment]
I haven't done it for a while, but I believe you can setup your own environment by creating :
```
/config/foo/settings.cfm
```
then doing:
```
?reload=foo&password=whatever
```

**Comment by andybellenie** [comment]
Hi @Andywmm9 

Wheels uses the term environment for development, testing, maintenance, and production, but it's not meant as a deployment environment, rather a particular mode, which you can switch between regardless of the deployment.

To manage settings specific to a deployment environment, I recommend using a switch statement in /config/settings.cfm rather than creating a new environment

E.g.

````
switch(cgi.server_name) {
	case "dev.mydomain.com":
		 set(datasourceName="dev_datasource");
		 break;
	case "staging.mydomain.com":
		 set(datasourceName="staging_datasource");
		 break;
	case "www.mydomain.com":
		 set(datasourceName="live_datasource");
		 break;
	default: 
		 throw(message="Invalid domain");
	}
````
